version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - pnpm-store:/root/.local/share/pnpm/store
    command: sleep infinity
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
  pnpm-store:
